# Generated by Django 5.1.3 on 2025-06-18 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nazwa')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikona')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='PackingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_weight', models.FloatField(blank=True, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clothes', 'Ubrania'), ('electronics', 'Elektronika'), ('toiletries', 'Kosmetyki'), ('documents', 'Dokumenty'), ('other', 'Inne')], max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('is_packed', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('main_luggage', 'Bagaż główny'), ('hand_luggage', 'Bagaż podręczny'), ('backpack', 'Plecak'), ('other', 'Inne')], default='main_luggage', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('packing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.packinglist')),
            ],
        ),
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa grupy')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('members', models.ManyToManyField(related_name='travel_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupa podróżna',
                'verbose_name_plural': 'Grupy podróżne',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, verbose_name='Cel podróży')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='Data zakończenia')),
                ('purpose', models.CharField(choices=[('mountains', 'Góry'), ('beach', 'Plaża'), ('city', 'Miasto'), ('camping', 'Camping'), ('business', 'Służbowy'), ('other', 'Inny')], max_length=50, verbose_name='Cel')),
                ('weather_info', models.JSONField(blank=True, default=dict, verbose_name='Informacje o pogodzie')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='core.travelgroup')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trips', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participated_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Podróż',
                'verbose_name_plural': 'Podróże',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='core.trip')),
            ],
            options={
                'verbose_name': 'Lista zakupów',
                'verbose_name_plural': 'Lista zakupów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200, verbose_name='Zadanie')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Termin')),
                ('priority', models.IntegerField(choices=[(1, 'Niski'), (2, 'Średni'), (3, 'Wysoki')], default=2, verbose_name='Priorytet')),
                ('is_done', models.BooleanField(default=False, verbose_name='Wykonane')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data wykonania')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.trip')),
            ],
            options={
                'verbose_name': 'Przypomnienie',
                'verbose_name_plural': 'Przypomnienia',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PreTripTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('high', 'Wysoki'), ('medium', 'Średni'), ('low', 'Niski')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.trip')),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.AddField(
            model_name='packinglist',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_lists', to='core.trip'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilość')),
                ('location', models.CharField(choices=[('handbag', 'Torba podręczna'), ('suitcase', 'Walizka'), ('backpack', 'Plecak'), ('other', 'Inne')], max_length=50, verbose_name='Lokalizacja')),
                ('weight', models.FloatField(default=0.0, verbose_name='Waga (kg)')),
                ('is_packed', models.BooleanField(default=False, verbose_name='Spakowane')),
                ('is_essential', models.BooleanField(default=False, verbose_name='Niezbędne')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category')),
                ('packed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packed_items', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.trip')),
            ],
            options={
                'verbose_name': 'Przedmiot',
                'verbose_name_plural': 'Przedmioty',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weather', 'Pogoda'), ('security', 'Bezpieczeństwo'), ('transport', 'Transport'), ('other', 'Inne')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.trip')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerty',
                'ordering': ['-created_at'],
            },
        ),
    ]
